MTES-MCT/zero-logement-vacant

- database/seeds/test/005-housing.ts
- frontend/src/utils/numberUtils.ts
- frontend/src/views/Campaign/CampaignView.tsx
- server/controllers/ownerController.test.ts
- server/models/UserApi.ts
- server/repositories/ownerRepository.ts
- shared/models/User.ts
Bugs corrigés : 
- page utilisateur pour les admins similaires à la page pour les collectivités (plus de boutons supprimer, ...)
- lorsqu'on accédait au détail d'une campagne en cours à partir de la liste des logements suivis, la récupération des logements se faisait à partir du campaign bundle dans le state qui n'était pas encore mis à jour avec celui pointé par l'URL. Au rafraichissement de la page le state étant préalablement vidé, il n'y avait plus de problème.
- le décompte du nombre de logements d'un propriétaire prenait en compte à tort les logements vacants de moins de deux ans
> Fix issues

- frontend/src/components/AppBreadcrumb/AppBreadcrumb.tsx
- frontend/src/components/HousingList/HousingList.tsx
- frontend/src/dsfr-fix.scss
- frontend/src/views/Campaign/CampainListView.tsx
- frontend/src/views/Home/EstablishmentHomeView.tsx
Speed up navigation using internal links (i.e. without reloading the page).
Avoid losing filters when going back or forth.
> Fix some links that should be using React Router links

- frontend/src/components/Aside/aside.module.scss
Replace the `width` transition by a `transform: translateX` transition to avoid a cluttered visual effect when closing the side panel.
> Replace Aside buggy width transition by a translation transition

- frontend/src/components/OwnerCard/OwnerCard.tsx
J'ai modifié le wording de la notification qui apparait quand l'adresse BAN du propriétaire est différente de l'adresse fiscale (validé par Nico et Lucas).
> Modification wording notification adresse proprio

- frontend/package.json
> Ajout licence MIT pour le frontend

- frontend/src/services/campaign.service.ts
- frontend/src/views/Group/GroupView.test.tsx
- server/controllers/campaignController.test.ts
- server/routers/protected.ts
Comply more with the REST API spec on Campaign API :
- rename `/api/campaigns/groups/:id` to `/api/campaigns/:id/groups`
It's also more readable in browser dev tools.
> Rename endpoint to create a group from a campaign

- frontend/src/services/event.service.ts
- server/controllers/eventController.test.ts
- server/controllers/eventController.ts
- server/routers/protected.ts
Replace `/api/events/owner/${id}` by `/api/owners/${id}/events` to :
- comply with the REST standard
- make it easier to read in the browser dev tools
Same with `/api/events/housing/${id}`.
> Refactor Events API

- .editorconfig
Afin d'unifier et favoriser une indentation du code homogène. éviter les EOF manquantes.
> Proposition : Ajout .editorconfig

- database/migrations/20240318223600-drafts-add-sender.ts
- frontend/src/components/Draft/DraftBody.tsx
- frontend/src/components/Draft/DraftSender.tsx
- frontend/src/components/Draft/SaveButton.tsx
- frontend/src/components/Draft/draft.module.scss
- frontend/src/hooks/useForm.tsx
- frontend/src/models/Draft.tsx
- frontend/src/models/Sender.tsx
- frontend/src/services/draft.service.ts
- frontend/src/utils/test/requestUtils.ts
- frontend/src/views/Campaign/CampaignDraft.tsx
- frontend/src/views/Campaign/test/CampaignView.test.tsx
- frontend/test/fixtures.test.ts
- server/controllers/draftController.ts
- server/controllers/test/draftController.test.ts
- server/models/DraftApi.ts
- server/models/SenderApi.ts
- server/repositories/draftRepository.ts
- server/repositories/senderRepository.ts
- server/repositories/test/draftRepository.test.ts
- server/templates/draft.css
- server/templates/draft.hbs
- server/test/testFixtures.ts
- shared/models/DraftDTO.ts
- shared/models/SenderDTO.ts
- shared/models/index.ts
- Add sender form
- When updating a draft
- update the sender if it exists (unique (name, establishment) pair)
- create a sender if not
- link the sender to the draft
- Add sender to the PDF preview
Merge this **after** #644
Recreated to avoid commit duplication when rebasing.
> Add draft sender

- .slugignore
Permet d'économiser la copie `node_modules` pour le déploiement de l'image.
**Taille de l'image**
Avant: 834Mo
Après: 480Mo
> Scalingo : ignore node_modules for frontend

- packages/utils/src/logger.ts
Les messages sont pris un par un car _pino_ affiche tous les messages au format _pino-pretty_, quel que soit l’env. On garde le prettify pour le dev, on laisse le comportement par défaut (NDJSON) pour la prod.
> Prettify logs in development and leave as JSON in production

- frontend/src/components/modals/HousingCreationModal/FillLocalId.tsx
Missins spaces today in the text
> Added non breaking space in the "Ajouter un logement" helpmessage 

- server/src/repositories/establishmentLocalityRepository.ts
- server/src/tasks/ceremaTask.ts
En m'appuyant sur le script original `server/src/infra/database/scripts/001-load-establishments_com_epci_reg_dep.sql`:
```
-- Link establishments <-> localities
INSERT INTO establishments_localities (
SELECT l.id, e.id
FROM localities l, establishments e
WHERE l.geo_code = any(e.localities_geo_code)
) ON conflict do nothing;
```
> fix: update establishments_localities table during CEREMA automation script execution and set available=true

- frontend/craco.config.js
- frontend/package.json
- frontend/src/components/GroupHeader/GroupHeader.test.tsx
- frontend/src/mocks/handlers/data.ts
- frontend/src/mocks/handlers/group-handlers.ts
- frontend/src/views/Campaign/test/CampaignView.test.tsx
- frontend/src/views/Group/GroupView.test.tsx
- frontend/src/views/Housing/test/HousingView.test.tsx
- frontend/src/views/HousingList/HousingListView.test.tsx
- frontend/src/views/Login/LoginView.test.tsx
- frontend/test/fixtures.test.ts
- frontend/tsconfig.build.json
- frontend/tsconfig.json
- packages/models/package.json
- packages/models/src/index.ts
- packages/models/tsconfig.build.json
- server/jest.config.ts
- server/src/controllers/ownerController.test.ts
- yarn.lock
`@faker-js/faker` was included with all of its locales in the front production build, which made it 11 MB ungzipped and 7.69 MB gzipped, taking up to 5.13 MB (66.7 % of the whole bundle size).
_react-scripts_ was compiling using `tsconfig.json`, which included test files, the mock API for frontend tests, etc. Typescript compilation was removed and replaced by a manual step before `react-scripts build`, using `tsconfig.build.json`.
Also, `@zerologementvacant/models` was split between `@zerologementvacant/models` (shared types) and `@zerologementvacant/models/fixtures` (shared factories for DTO types, for test purposes).
The resulting production bundle does not include `@faker-js/faker` from the build, as intended, which reduces its size down to 2.55 MB ungzipped, 530 KB gzipped.
> Reduce build size

- package.json
- packages/draft/package.json
- packages/draft/src/pdf.ts
- packages/draft/src/templates/draft/draft.css
- packages/draft/src/templates/draft/draft.hbs
- packages/draft/src/templates/draft/index.ts
- packages/draft/src/test/pdf.test.ts
- packages/utils/package.json
- packages/utils/src/stream.ts
- queue/src/workers/generate-mails.ts
- server/src/controllers/draftController.ts
- server/src/infra/database/seeds/development/20241028160748_drafts.ts
- server/src/scripts/import-lovac/housings/test/housing-processor.test.ts
- server/src/test/testFixtures.ts
- yarn.lock
Given a draft and a lot of housings :
Open a browser and render the HTML content using puppeteer.
The images are extracted from the HTML and saved for later.
The images are hidden in the HTML to avoid rendering them in the PDF.
Transform HTML to PDF and return the result as a PDFDocument.
Clean up the browser.
Merge the pages into a single PDF.
For each image, embed it in the PDF and reference it on each page at its correct position.
Save the final PDF.
- Handles JPEG and PNG
- Handles variable positions for instance when there are one or more logo
- Avoids copying the same images over and over. Embed them once, reference them later
- Handles huge quantities using Node `Streams`
> Handle large campaign generation

- queue/package.json
- queue/src/server.ts
- yarn.lock
Active un certain nombre de protections (https://helmetjs.github.io/). Déjà utilisé par le `server`
> fix: add helmet on queue to improve security

- frontend/src/mocks/handlers/housing-handlers.ts
- frontend/src/services/housing.service.ts
- server/src/controllers/housingController.ts
- server/src/routers/protected.ts
- Corrige le comptage pour les filtre multi-propriétaire et le filtre logement > taxé
- Refactoring de l'endpoint API sur le comptage (`POST` > `GET`)
> fix: boolean filters isTaxed and multiOwners

- frontend/src/components/FileUpload/FileUpload.tsx
- server/src/middlewares/upload.ts
Renvoi une 400 quand le format n'est pas autorisé, une alerte est affichée sur le front. Nécessaire pour les anciens navigateurs qui ne supportent pas l'attribut `accept` d'une `input` de type `file`.
> fix: Filter mimetype for logos on server side

- frontend/src/views/Analysis/AnalysisView.tsx
> Increase the analysis iframe’s height to avoid scrolling

- .talismanrc
- analytics/.gitignore
- analytics/dagster/src/assets/populate_edited_owners_ban_addresses.py
- analytics/dagster/src/assets/populate_housings_ban_addresses.py
- analytics/dagster/src/assets/populate_owners_ban_addresses.py
- analytics/dagster/src/definitions.py
- analytics/dagster/src/jobs/edited_owners_ban_addresses_job.py
- analytics/dagster/src/jobs/housings_ban_addresses_job.py
- analytics/dagster/src/jobs/owners_ban_addresses_job.py
- analytics/dagster/src/requirements.txt
- analytics/dagster/src/resources/database_resources.py
This pull request includes several changes to improve the handling of BAN address data. The changes focus on updating file handling, modifying function implementations, and enhancing logging and error handling.
* Switched from CSV to Parquet format for better performance and efficiency in `populate_owners_ban_addresses.py`.
* Added `.parquet` to `.gitignore` to exclude Parquet files from version control.
* Updated function names to better reflect their purpose.
* Modified the `parse_api_response_and_insert_owners_addresses` function to handle Parquet files and improved the database insertion logic.
* Enhanced logging to provide more detailed information about the process and errors.
* Improved error handling for file operations and API requests.
* Updated checksums in .talismanrc to …
> Optimize BAN address processing (Parquet, logging, error handling) – tested locally with prod data, ready for deployment

- frontend/src/components/RichEditor/useVariablePlugin.ts
This pull request includes several updates to the `useVariablePlugin` function in the `frontend/src/components/RichEditor/useVariablePlugin.ts` file to improve whitespace handling around `VariableNode` elements. The most important changes include adding a new utility function for cleaning up whitespace, updating the node insertion logic, and modifying the mutation listener.
Whitespace handling improvements:
* Added the `cleanUpWhitespace` function to ensure proper whitespace handling around `VariableNode` elements.
* Updated the `isWhitespaceBefore` and `isWhitespaceAfter` functions to handle cases where the node is null or contains whitespace at the start or end of the text content.
Node insertion logic:
* Updated the `useVariablePlugin` function to insert whitespace before and after a …
> fix: properly handle VariableNode deletion in Lexical

- .talismanrc
- analytics/dagster/src/assets/populate_edited_owners_ban_addresses.py
- analytics/dagster/src/assets/populate_owners_ban_addresses.py
- analytics/dagster/src/definitions.py
This pull request includes significant updates to the `analytics/dagster` assets, focusing on simplifying and improving the processing of owner and edited owner BAN addresses. The changes streamline the code by merging multiple steps into single functions and enhancing error handling.
Key changes include:
* [`analytics/dagster/src/assets/populate_edited_owners_ban_addresses.py`](diffhunk://#diff-e29d90e83c642788f319657055c05227765a29d504629b8962f0df6e8fc3b590L1-R51): Combined multiple asset functions into `process_and_update_edited_owners`, which now handles retrieving, processing, and updating edited owners in one step. This change includes enhanced logging and error handling for better traceability. 
* [`analytics/dagster/src/assets/populate_owners_ban_addresses.py`](diffhunk://#diff-1d1 …
> Fix: merge owner processing steps and handle BAN ID updates

- frontend/src/components/GroupHeader/GroupHeader.tsx
Modification du wording des instructions pour créer un premier groupe suite au changement du nom du CTA "Ajouter dans un groupe" devenu "Exporter ou contacter" dans le nouveau parcours de création de groupes/campagnes.
> modif_wording_GroupHeader

- frontend/src/views/HousingList/HousingListView.tsx
The former message didn't fit when a user is on the map (example here: https://eu.posthog.com/project/23240/replay/019585cc-5032-73b3-b0ce-3e59cc895763?t=133)
> Updated export or contact text 

- server/src/repositories/housingRepository.ts
Fix division by zero in vacancy rate filters
This PR addresses a potential division by zero issue in the vacancyRates filtering logic.
- Wrapped all vacancy rate comparisons in a housing_count > 0 guard clause to avoid division by zero errors.
- Ensured floating-point division by using 100.0 instead of 100 to avoid unintended integer truncation.
> fix: avoid division by zero

- queue/.env.example
- queue/package.json
- queue/src/config.ts
- queue/src/events/index.ts
- queue/src/scripts/job-manager-cli.ts
- queue/src/sentry.ts
- server/src/infra/queue.ts
- yarn.lock
This PR introduces a utility script to simplify campaign job management in the queue. The script allows:
- 🔍 Searching jobs by campaignId
- ❌ Viewing job errors (failed state)
- 🔁 Retrying existing jobs or 🔨 creating new ones from their data
In addition, to fix timeout-related failures on long-running jobs, the timeout has been increased from 30 seconds to 5 minutes.
> Queue management

- server/src/infra/database/migrations/20250716132309_precision-housing-events-fix-constraints.ts
- server/src/infra/database/migrations/20250716132616_events-index-type.ts
- server/src/infra/database/migrations/20250716132835_owner-events-fix-foreign-key-constraints.ts
- server/src/infra/database/migrations/20250716150612_housing-events-fix-index.ts
- server/src/infra/database/migrations/20250716152359_campaign-events-remove-primary.ts
- server/src/infra/database/migrations/20250716154722_campaign-housing-events-fix-constraints.ts
- server/src/infra/database/migrations/20250716154907_group-housing-events-fix-constraints.ts
- server/src/infra/database/migrations/20250716155117_housing-owner-events-fix-constraints.ts
The main table `events` has an `id UUID PK`.
The event-related events should have an `event_id UUID FK PK`. There was no primary key constraint.
> Fix event-related tables constraints

- frontend/src/components/modals/GroupCampaignCreationModal/GroupCampaignCreationModal.tsx
Problem is that today, there is no space btwn the sentence and the groupe name. here is my proposal.
> Added a space in the create a campaign from a group modal

- frontend/src/components/OwnerCard/OwnerCardNext.tsx
Modification du texte "(Source : BAN)" en "(Source : Base Adresse Nationale)" pour expliciter l'acronyme sur la fiche logement.
> Modif du mot "BAN" pour l'expliciter
