frontend/src/services/campaign.service.ts

MEP 04/04/22

---

frontend/src/services/statistic.service.ts
frontend/src/store/actions/statisticAction.tsx
frontend/src/store/reducers/statisticReducer.tsx
frontend/src/views/Stats/StatsView.tsx
server/controllers/statController.ts
server/routers/unprotected.ts

MEP 25/05/22 #2

---

server/controllers/statController.ts

MEP 25/05/22 #3

---

frontend/src/services/housing.service.ts
frontend/src/store/actions/campaignAction.tsx
server/controllers/housingController.ts

Fix issue on updating housing list from a search query

MEP 30/06/22

---

.docker/README.md
.docker/docker-compose.yml
.docker/setup.sh
README.md
database/migrations/037-users-add-soft-deletion.ts
database/scripts/002-load-data.sql
frontend/src/hooks/useAvailableEstablishmentOptions.tsx
frontend/src/services/user.service.ts
frontend/src/store/actions/userAction.tsx
frontend/src/store/reducers/userReducer.tsx
frontend/src/views/User/UserListView.tsx
frontend/src/views/User/user-list.module.scss
package-lock.json
package.json
server/controllers/userController.test.ts
server/controllers/userController.ts
server/errors/http-error.ts
server/errors/user-not-found-error.ts
server/index.ts
server/middlewares/error-handler.ts
server/middlewares/test/error-handler.test.ts
server/middlewares/test/validator.test.ts
server/middlewares/validator.ts
server/repositories/db.ts
server/repositories/userRepository.ts
server/routers/protected.ts

La suppression d'un utilisateur suppose son existence préalable.
Avec la gestion d'erreur actuelle, on ne peut pas différencier une _exception unchecked_ (type connexion perdue) d'une erreur métier (type utilisateur non trouvé).
Il y a donc un risque de crash si l'utilisateur qu'on tente de supprimer n'est pas trouvé.
Solution 1 : on revoit la gestion d'erreur
**Solution 2 : on catch l'erreur _utilisateur non trouvé_ et on se débrouille pour la vérifier**

Remove user

---

.github/workflows/github-actions.yml
package-lock.json
package.json
server/server.ts
server/services/mailService.ts
server/utils/config.test.ts
server/utils/config.ts
server/utils/sentry.ts

Use `convict` to validate the configuration **before** the application starts. It aims to avoid runtime errors related to configuration.
Add config types.

Add config validation and management

---

frontend/src/App.tsx
frontend/src/components/AppHeader/AppHeader.test.tsx
frontend/src/components/AppHeader/AppHeader.tsx
frontend/src/components/modals/CampaignCreationModal/CampaignCreationModal.test.tsx
frontend/src/store/reducers/authenticationReducer.tsx
frontend/src/views/HousingList/HousingListView.test.tsx
frontend/src/views/Login/LoginView.tsx

Gestion de la déconnexion automatique lorsque le token JWT est expiré pour rediriger vers la page de login avec message d'invitation à se reconnecter.

Handle log out with a redirection to the login page

---

frontend/src/hooks/useDocumentTitle.tsx
frontend/src/views/Accessibility/AccessibilityView.tsx
frontend/src/views/Account/AccountCreationView.tsx
frontend/src/views/Account/AccountPasswordView.tsx
frontend/src/views/Account/ForgottenPasswordView.tsx
frontend/src/views/Account/ResetPasswordView.tsx
frontend/src/views/Campaign/CampaignView.tsx
frontend/src/views/Campaign/CampainListView.tsx
frontend/src/views/Dashboard/DashboardView.tsx
frontend/src/views/GeoPerimeter/GeoPerimeterView.tsx
frontend/src/views/Home/HomeView.tsx
frontend/src/views/Housing/HousingView.tsx
frontend/src/views/HousingList/HousingListView.tsx
frontend/src/views/Login/LoginView.tsx
frontend/src/views/Monitoring/MonitoringDetailView.tsx
frontend/src/views/Monitoring/MonitoringView.tsx
frontend/src/views/Owner/OwnerView.tsx
frontend/src/views/Proprietaire/ProprietaireView.tsx
frontend/src/views/Resources/ResourcesView.tsx
frontend/src/views/Stats/StatsView.tsx
frontend/src/views/User/UserListView.tsx

Enhance navigation by providing a title to each important view.

Add document title to views

---

frontend/src/views/Establishment/EstablismentView.tsx

Disable temporary locality taxes

MEP 26/01/23

---

database/seeds/dummy/004-buildings.ts
database/seeds/production/003-buildings.ts

Insertion via SQL au lieu de charger les données en mémoire.

Count vacant housing per building

---

frontend/src/components/AppHeader/AppHeader.tsx
frontend/src/components/EstablishmentSearchableSelect/EstablishmentSearchableSelect.tsx
frontend/src/components/Inbox/InboxMessageList.tsx
frontend/src/hooks/test/useSelection.test.ts
frontend/src/hooks/useSelection.tsx
frontend/src/views/Campaign/CampaignToValidate.tsx

Fixed hasSelected in case of selecting all and then deselecting one item.

Fix use selection hook

---

frontend/src/components/AppBreadcrumb/AppBreadcrumb.tsx
frontend/src/components/HousingList/HousingList.tsx

Premier jet de refactor sur le breadcrumb pour simplifier sa lecture.

Clarify breadcrumb

---

database/migrations/064-settings-add-inbox-enabled.ts
frontend/src/hooks/useSettings.tsx
frontend/src/services/settings.service.ts
frontend/src/store/actions/settingsAction.tsx
frontend/src/views/Home/OwnerEstablishmentHomeView.tsx
server/controllers/settingsController.test.ts
server/controllers/settingsController.ts
server/models/SettingsApi.ts
server/repositories/settingsRepository.ts
server/routers/protected.ts
server/routers/unprotected.ts
server/test/testFixtures.ts
shared/models/Settings.ts

Pour cacher le formulaire de contact propriétaire pour Paris.

Hide owner contact form if the establishment disabled it

---

.docker/setup.sh
frontend/src/colors.scss
frontend/src/components/ExtendedToggle/ExtendedToggle.tsx
frontend/src/components/Map/Map.tsx
frontend/src/components/Map/MapControls.tsx
frontend/src/components/Map/Perimeters.tsx
frontend/src/components/Map/map-controls.module.scss
frontend/src/models/GeoPerimeter.tsx
frontend/src/models/Identifiable.tsx
frontend/src/utils/arrayUtils.ts
frontend/src/utils/compareUtils.ts
frontend/src/utils/test/arrayUtils.test.ts
frontend/src/views/HousingList/HousingListView.tsx

- Display perimeters on the map
- Add a control to toggle visibility

Display perimeters on the map

---

frontend/src/components/Map/Map.tsx
frontend/src/utils/arrayUtils.ts
frontend/src/views/HousingList/HousingListView.tsx

- Included perimeters are green, excluded perimeters are red and the remaining ones stay gray
- Add map legend

Fix perimeters

---

scripts/import-poorly-insulated-housing/index.ts

Hotfix MEP 03/08/2023

---

server/server.ts

Configure cors to enable viewing session from matomo

MEP 24/01/24 #2

---

frontend/src/components/Map/Map.tsx

Add copyright attributions to the Map component

---

frontend/src/App.tsx
frontend/src/components/modals/HousingOwnersModal/HousingAdditionalOwnerSearchResults.tsx
frontend/src/services/api.service.ts
frontend/src/services/campaign.service.ts
frontend/src/services/contact-point.service.ts
frontend/src/services/dashboard.service.ts
frontend/src/services/datafoncier.service.ts
frontend/src/services/establishment.service.ts
frontend/src/services/event.service.ts
frontend/src/services/geo.service.ts
frontend/src/services/group.service.ts
frontend/src/services/housing.service.ts
frontend/src/services/locality.service.ts
frontend/src/services/note.service.ts
frontend/src/services/owner-prospect.service.ts
frontend/src/services/owner.service.ts
frontend/src/services/settings.service.ts
frontend/src/services/signup-link.service.ts
frontend/src/services/user-account.service.ts
frontend/src/services/user.service.ts
frontend/src/store/store.tsx

Rework api service to use a single API slice as recommended with [ RTK Query  ](https://redux.js.org/tutorials/essentials/part-7-rtk-query-basics#defining-an-api-slice)
In addition, it provides global management of the loading bar (in this PR) and errors (later).

Use a single api slice

---

frontend/src/components/HousingDetails/HousingDetailsSubCardLocation.tsx
frontend/src/components/HousingListFilters/HousingListFiltersSidemenu.tsx
server/controllers/housingExportController.ts

Changed "Emplacement" for "Localisation" wording

---

frontend/src/components/Label/label.module.scss

Documentation here: 
https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-de-l-identite-de-l-etat/couleurs-utilisation-dans-le-dsfr/

Updated label color from dark theme setup to light theme setup

---

frontend/src/App.scss

documentation here: https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-de-l-identite-de-l-etat/couleurs-utilisation-dans-le-dsfr/
Same problem as here but at a different place in the SaaS: https://www.notion.so/zlv/90627b807b934b68a30aafc9ed1abaa4?v=dcf8fc5f4a6745a4b29dbde27ff34ccf&p=c4b6b02a24994915816e2ceb9dcdc607&pm=s

Updated the color's labels on the house card

---

server/src/controllers/campaignController.test.ts
server/src/controllers/campaignController.ts
server/src/models/CampaignApi.ts

`validatedAt` should be set only when the campaign gets validated, not before.

Fix the campaign validatedAt timestamp

---

.talismanrc
server/src/infra/database/seeds/development/df-housing-nat.ts
server/src/infra/database/seeds/development/df-owners-nat.ts
server/src/infra/database/seeds/test/df-housing-nat.ts
server/src/infra/database/seeds/test/df-owners-nat.ts
server/src/repositories/datafoncierHousingRepository.ts
server/src/repositories/datafoncierOwnersRepository.ts
server/src/scripts/duplicate-database/script.sh
server/src/scripts/import-datafoncier-to-zlv/fix-geo.ts
server/src/scripts/import-datafoncier-to-zlv/fix-plot_id.ts
server/src/scripts/import-datafoncier-to-zlv/index.ts

Housing creation should fetch data from `df_housing_nat` and `df_owners_nat`

Fix housing creation

---

frontend/src/views/Resources/ResourcesView.tsx

Textes de chaque rubrique raccourcis pour améliorer l'accessibilité

Modif_wording_resources

---

server/src/infra/database/seeds/development/20240404235457_users.ts
server/src/repositories/establishmentRepository.ts
server/src/services/ceremaService/consultStructureService.ts
server/src/test/testFixtures.ts

- Generate a few users for each available establishment
- Fixes the campaign generation because there was no user to link to the generated campaigns

Enhance seeders

---

.talismanrc
frontend/src/models/Housing.tsx
frontend/src/models/test/Housing.test.ts

feat: change source label display

---

frontend/public/.htaccess

Les redirections sont faites côtés Wagtail dans la configuration.

chore: remove useless redirects

---

frontend/src/components/modals/HousingOwnersModal/HousingOwnersModal.tsx
frontend/src/hooks/useHousing.tsx
frontend/src/mocks/handlers/data.ts
frontend/src/mocks/handlers/housing-handlers.ts
frontend/src/mocks/handlers/index.ts
frontend/src/mocks/handlers/note-handlers.ts
frontend/src/mocks/handlers/owner-handlers.ts
frontend/src/views/Housing/test/HousingView.test.tsx

Test owner update

---

frontend/src/views/Account/AccountCreation/AccountEmailCreationView.tsx

feat: alert message on account creation form

---

.talismanrc
frontend/src/views/Campaign/CampaignSending.tsx
frontend/src/views/Campaign/test/CampaignView.test.tsx
queue/src/events/index.ts
queue/src/jobs.ts
queue/src/workers/generate-mails.ts
server/src/controllers/test/serverSentEventController.test.ts
server/src/repositories/campaignRepository.ts

Bullmq minor upgrade removed support for colon-separated queue names
See https://github.com/taskforcesh/bullmq/issues/2718

Rename queues because of the bullmq upgrade

---

frontend/src/views/Account/AccountCreation/AccountAccessForbiddenView.tsx
frontend/src/views/Account/AccountCreation/AccountEmailCreationView.tsx

Modif du wording de la page qui s'affiche en cas de mail non reconnu suite au clic sur le lien de vérification par mail

Autres modifs du wording suite à la MEP du portailDF du Cerema

---

frontend/src/components/modals/HousingCreationModal/FillLocalId.tsx
frontend/src/views/HousingList/HousingListView.test.tsx

Move housing creation label to the input label

---

frontend/src/views/Resources/ResourcesView.tsx
frontend/src/views/Resources/resources.module.scss

Fix resource icons’ colors accessibility

---

frontend/src/components/modals/CampaignCreationModal/CampaignCreationModal.tsx
frontend/src/components/modals/OwnerEditionModal/OwnerEditionModal.tsx
frontend/src/components/modals/PrecisionsModal/PrecisionsModal.tsx

Modals should be closed by default to avoid scroll issues

Fix scroll issues

---

frontend/src/components/modals/HousingCreationModal/FillLocalId.tsx

Modification du wording de la modale d'ajout d'un logement pour préciser le format attendu

Modif_wording_housingcreation_modal

---

frontend/src/components/modals/GeoPerimetersModal/GeoPerimetersModal.tsx

Modification du wording de la modale périmètre pour : raccourcir le texte + spécifier 500 entités max + correction coquille dans le message de confirmation

Modif_wording_geoperimeters_modal

---

frontend/src/components/Draft/DraftSendingDate.tsx

Modification du composant :
- titre au niveau la date d'envoi
- suppression du message d'alerte en-dessous du champ

modif wording component

---

frontend/src/components/HousingFiltersBadges/HousingFiltersBadges.tsx
frontend/src/hooks/useLocalityList.tsx
frontend/src/models/HousingFilters.tsx
frontend/src/models/HousingState.tsx
frontend/src/views/Housing/test/HousingView.test.tsx
server/tsconfig.json

Add badge labels

---

frontend/src/components/Group/Group.tsx
frontend/src/models/User.tsx
frontend/src/models/test/User.test.tsx

Display the user’s first and last name if defined, otherwise their email

---

frontend/src/components/OwnerEditionSideMenu/OwnerEditionSideMenu.tsx
frontend/src/views/Campaign/test/CampaignView.test.tsx

The button currently doesn't fit

Updated "éditer l'adresse" button in campaign view 

---

server/src/models/PrecisionApi.ts

Le nom du dispositif "RHI - THIRORI" devient "ORI ou RHI - THIRORI".

modif du wording d'un dispositif

---

packages/api-sdk/src/campaign-api.ts
queue/src/workers/generate-mails.ts
server/src/controllers/housingController.ts
server/src/controllers/housingExportController.ts
server/src/infra/config.ts
server/src/repositories/housingRepository.ts
server/src/repositories/ownerRepository.ts
server/src/repositories/test/ownerRepository.test.ts
server/src/utils/excelUtils.ts

Rework campaign and group export.
Improve overall housing list and stream performance.
Rationalize the generated _xlsx_ file : removed obsolete columns, replacing some by new ones (housing evolutions, mechanisms, blocking points...).

Fix housing export
